apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-minimal-notebook-anaconda
  labels:
    opendatahub.io/notebook-image: "false"
    opendatahub.io/modified: "false"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/Xaenalt/s2i-minimal-notebook"
    opendatahub.io/notebook-image-name: "Anaconda-enabled notebook. Requires Anaconda license key."
    opendatahub.io/notebook-image-desc: "Notebook with Anaconda tools instead of pip."
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/modh/s2i-minimal-notebook-anaconda
    from:
      kind: DockerImage
      name: quay.io/modh/s2i-minimal-notebook-anaconda:py38
    name: "py38"
    referencePolicy:
      type: Source
